runtime: python38

handlers:
  - url: /static
    static_dir: dist/browser

  - url: /(.*\.(js|css|png|jpg|ico|json|svg))
    static_files: dist/browser/\1
    upload: dist/browser/.*

  - url: /.*
    static_files: dist/browser/index.html
    upload: dist/browser/index.html
